### ISSUE TITLE
Debugging task failures

### ISSUE THREAD

**Issue by slayer152** [timopruesse/machine_setup#72]
Hello, 

Does this program generate a log file or can it display the stdout, stderr messages of the commands run for each task? For e.g., with the below config, I can that the task failed but I don't know why it failed when I ran the config with machine_setup (I was able to figure out that the failure was because the executable was called `dym` instead of `didyoumean` in the `mv` command only by manually running each command in the shell). Thank you.

cmd:
```machine_setup -c <path_to_config.yml> --select install --level=debug```

Error:
```
[                                                  ] 0/1: ⏳ didyoumean: run                                                                                                                run: ERROR

   |> ERR

[==================================================] 1/1: ❌ didyoumean ➡️ ERR                                                                                                               Task  didyoumean  failed
```

config.yml
```
---
default_shell: bash
tasks:
  didyoumean:
    commands:
      - run:
          commands:
            install:
              - cargo install didyoumean
              - mkdir -p ~/.local/bin
              - mv ~/.cargo/bin/didyoumean ~/.local/bin
```

**Comment by timopruesse** [comment]
Hey,
Sorry for the late response!

Currently, it doesn't generate log files. However, it should display stderr information when log level "debug" is set. I'll look into it when I find time.

**Comment by timopruesse** [comment]
Errors will be logged (to the terminal) correctly in the next release (v1.3.3):
![image](https://user-images.githubusercontent.com/13467720/220438810-bef78d20-e15f-4062-80d0-1d6b2f778a06.png)
